### PR TITLE
fix(tools): Do not return default when type is struct

### PR DESCRIPTION
**Pull request by riemannulus**
Fix these error:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Tools.Mpt.Add(String alias, String uri, IConfigurationService`1 configurationService) in C:\Users\riema\Documents\Workspaces\libplanet\Libplanet.Tools\Mpt.cs:line 172
```

### CODE REVIEW

**Comment by longfin** [comment]
It seems fix NRE but I can't export states via URI yet.

```
PS C:\Users\X1E\libplanet\Libplanet.Tools> dir "C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1"


    Directory: C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----        2020-10-23  오후 2:54                block
d----        2020-10-23  오후 2:54                chain
d----        2020-10-23  오후 2:54                stagedtx
d----        2020-10-23  오후 2:54                state
d----        2020-10-23  오후 2:54                state_hashes
d----        2020-10-23  오후 2:54                stateref
d----        2020-10-23  오후 2:54                states
d----        2020-10-23  오후 2:54                tx
-a---        2020-10-23  오후 6:36              0 000003.log
-a---        2020-10-23  오후 6:36             16 CURRENT
-a---        2020-10-23  오후 6:36             36 IDENTITY
-a---        2020-10-23  오후 6:36              0 LOCK
-a---        2020-10-23  오후 6:36          19938 LOG
-a---        2020-10-23  오후 6:36             13 MANIFEST-000001
-a---        2020-10-23  오후 6:36           5151 OPTIONS-000005

PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt export "rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2"
The alias, 'rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1' doesn't exist. Please pass correct uri or alias.
```

**Comment by riemannulus** [comment]
@longfin Dir must contained `states` at the end. Can you try with `C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states` ?

**Comment by longfin** [comment]
> @longfin Dir must contained `states` at the end. Can you try with `C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states` ?

Same. 😢 

```
PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt export "rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2"
The alias, 'rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states' doesn't exist. Please pass correct uri or alias.
PS C:\Users\X1E\libplanet\Libplanet.Tools> dir C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states


    Directory: C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---        2020-10-23  오후 2:21       67376376 000054.sst
-a---        2020-10-23  오후 2:21       23492819 000055.sst
-a---        2020-10-23  오후 2:31        1254238 000057.sst
-a---        2020-10-23  오후 2:54        1251353 000060.sst
-a---        2020-10-23  오후 2:56        4407000 000062.log
-a---        2020-10-23  오후 2:54             16 CURRENT
-a---        2020-10-19  오후 9:49             36 IDENTITY
-a---        2020-10-23  오후 2:54              0 LOCK
-a---        2020-10-23  오후 2:54          22686 LOG
-a---        2020-10-19  오후 9:49          19973 LOG.old.1603112057298730
-a---        2020-10-19  오후 9:54          22308 LOG.old.1603112093778188
-a---        2020-10-19  오후 9:54         172252 LOG.old.1603186759544486
-a---        2020-10-20  오후 6:39          32494 LOG.old.1603281628121691
-a---        2020-10-21  오후 9:00          49157 LOG.old.1603365588895827
-a---        2020-10-22  오후 8:19          28186 LOG.old.1603366534500220
-a---        2020-10-22  오후 8:35          28175 LOG.old.1603369634518769
-a---        2020-10-22  오후 9:27          28189 LOG.old.1603370702952962
-a---        2020-10-22  오후 9:45          33313 LOG.old.1603373698991137
-a---        2020-10-22 오후 10:34         524260 LOG.old.1603429830494232
-a---        2020-10-23  오후 2:10          22697 LOG.old.1603429886784586
-a---        2020-10-23  오후 2:11          21263 LOG.old.1603430187513784
-a---        2020-10-23  오후 2:16          22698 LOG.old.1603430481047830
-a---        2020-10-23  오후 2:21          27658 LOG.old.1603431109781139
-a---        2020-10-23  오후 2:31          22675 LOG.old.1603432470485716
-a---        2020-10-23  오후 2:54            431 MANIFEST-000061
-a---        2020-10-23  오후 2:31           5165 OPTIONS-000061
-a---        2020-10-23  오후 2:54           5165 OPTIONS-000064
```

**Comment by longfin** [comment]
`mpt add` and `mpt export` combination works well. 😅 

```pwsh
PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt add "9c-beta-9-rc1" "rocksdb+file://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1\states"
{"Mpt":{"Aliases":{"9c-beta-9-rc1":"rocksdb\u002Bfile://C:\\Users\\X1E\\AppData\\Local\\planetarium\\9c-beta-9-rc1\\states"}}}
PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt add "9c-beta-9-rc1" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2"
It seems the uri is not valid. (exceptionMessage: Invalid URI: The format of the URI could not be determined.)
PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt export "9c-beta-9-rc1" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2"
;; <messy output>
```

**Review by longfin — APPROVED** [review]

**Review by moreal — DISMISSED** [review]

**Review by limebell — APPROVED** [review]

**Review by area363 — DISMISSED** [review]

**Review by earlbread — APPROVED** [review]

**Comment by moreal** [comment]
> 
> ....
> ```
> PS C:\Users\X1E\libplanet\Libplanet.Tools> dotnet run -- mpt export "rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2"
> The alias, 'rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1' doesn't exist. Please pass correct uri or alias.
> ```

Hello @longfin . I found why it doesn't work well so I left the reason here. Actually `Libplanet.Tools` ' subcommand `mpt` supports two ways to present key value store. The first one is to use alias registed with `mpt add` and another one is the full URI (e.g., `rocksdb://C:\Users\X1E\AppData\Local\planetarium\9c-beta-9-rc1" "5199af4fdcf90ed10dd213dd853c3cb666f60df20224874eb5fc7a1d45cc13a2`). And it distinct what way used to present the given arugment, with `Uri.IsWellFormedUriString(...)`. It works like below execution result.


> > Uri.IsWellFormedUriString("file:///C:\\foo", UriKind.Absolute)
> false
> > Uri.IsWellFormedUriString("file:///C:/foo", UriKind.Absolute)
> true
> > Uri.IsWellFormedUriString("file://C:/foo", UriKind.Absolute)
> false

So. if you want to use it in full URI format, you must attach `/` at the front of the path and replace `\` with `/`. In your case, like this, `rocksdb:///C:/Users/X1E/AppData/Local/planetarium/9c-beta-9-rc1`.

**Review by moreal — APPROVED** [review]

**Review by earlbread — APPROVED** [review]

**Review by longfin — APPROVED** [review]

**Pull request merged**
