### PR TITLE
Motivate miners to upgrade protocol version

### PR DESCRIPTION
**Pull request by dahlia**
This implements #1155.

### CODE REVIEW

**Comment by dahlia** [comment]
@planetarium/libplanet PTAL.

**Review by moreal — APPROVED** [review]
As a comment, 721e7d22a334de457592b1eb129e8a46870bf3f0 seems having changelog changes but commit message having `[changelog skip]`.

**Comment by dahlia** [comment]
@planetarium/libplanet Rebased. PTAL again.

**Review by limebell — APPROVED** [review]

**Comment by dahlia** [comment]
@planetarium/libplanet Rebased. PTAL again.

**Review by moreal — APPROVED** [review]

**Review by limebell — APPROVED** [review]

**Pull request merged**
