### PR TITLE
Replace `UserContext` with .NET DI

### PR DESCRIPTION
**Pull request by xet-a**
`UserContext` are replaced with .NET DI by removing a `IStore` variable and put it to parameterized constructor.

close : #1936

### CODE REVIEW

**Review by dahlia — APPROVED** [review]

**Comment by longfin** [comment]
I think that we need to check the tests for `Libplanet.Explorer.GraphTypes` 🤔  cc @moreal

**Comment by moreal** [comment]
> I think that we need to check the tests for `Libplanet.Explorer.GraphTypes` 🤔 cc @moreal

It failed because the `BlockTypeTest` used `GraphQLTestUtils.ExecuteQueryAsync` but it doesn't support DI. The implementation code is:

```csharp
public static Task<ExecutionResult> ExecuteQueryAsync<TObjectGraphType>(
            string query,
            IDictionary<string, object> userContext = null,
            object source = null)
            where TObjectGraphType : IObjectGraphType, new()
        {
            var documentExecutor = new DocumentExecuter();
            return documentExecutor.ExecuteAsync(new ExecutionOptions
            {
                Query = query,
                Schema = new Schema
                {
                    Query = new TObjectGraphType(),
                },
                UserContext = userContext,
                Root = source,
            });
        }
```

Originally, the function expected that all GraphQL types would have a no-arguments constructor. But the assumption was broken so this pull request's CI was also broken.
To resolve it, it should rewrite `GraphQLTestUtils.ExecuteQueryAsync` with `ServiceProvider` and `ServiceCollection` 🤔 

In `NineChronicles.Headless.Tests`, it does in [`NineChronilces.Headless.Tests.GraphQLTestUtils`](
https://github.com/planetarium/NineChronicles.Headless/blob/221fb9887751a7e20e639075d74e9ee26be75471/NineChronicles.Headless.Tests/GraphQLTestUtils.cs#L9-L58). Make sure it is just an example so do it your way if you're familiar with .NET DI and know a good pattern 👍🏻

**Comment by dahlia** [comment]
First of all, could you rebase your changes on the latest main branch?

**Comment by longfin** [comment]
> Originally, the function expected that all GraphQL types would have a no-arguments constructor. But the assumption was broken so this pull request's CI was also broken. To resolve it, it should rewrite `GraphQLTestUtils.ExecuteQueryAsync` with `ServiceProvider` and `ServiceCollection` 🤔

@moreal Thanks for detailed comments. but on second thought, lookup with `ServiceCollection` or `ServiceCollection` seems a little bit weird if we want to write a unit test for just `BlockType`, because DI's main concept (injecting dpes on constructor) aims  easy testing in general... 😕 

Nevertheless, it can be a long story to take in this issue and PR. at least, we need to aim small scope of code changes here and continue to discussion about GQL testing on the other issue. 😇 

> In NineChronicles.Headless.Tests, it does in [NineChronilces.Headless.Tests.GraphQLTestUtils](https://github.com/planetarium/NineChronicles.Headless/blob/221fb9887751a7e20e639075d74e9ee26be75471/NineChronicles.Headless.Tests/GraphQLTestUtils.cs#L9-L58). Make sure it is just an example so do it your way if you're familiar with .NET DI and know a good pattern 👍🏻

I think that using `NineChronilces.Headless.Tests.GraphQLTestUtils`'s approach as is can be quite tricky, because `.AddLibplanetExplorer()` wasn't implemented in Libplanet, but [in `NineChronicles.Headless`
](https://github.com/planetarium/NineChronicles.Headless/blob/31f865d9c9f86e564fc4668d3fdd2a42f1df8371/NineChronicles.Headless/GraphQLServiceExtensions.cs#L52-L67). thus it may be more easier to add an API that directly receives the `ObjectGraphType` that we want to test by `ExecuteAsync()` instead of using a generic method.

**Comment by longfin** [comment]
Just note: even in 0.40.0, `BlockTypeTest.Query()` is failing under modifying a target query like as below. 😅 

```csharp
            var query =
                @"{
                    index
                    hash
                    nonce
                    difficulty
                    totalDifficulty
                    miner
                    publicKey
                    timestamp
                    stateRootHash
                    signature
                    previousBlock { index }
                }";
```
```
Xunit.Sdk.NullException
Assert.Null() Failure
Expected: (null)
Actual:   ExecutionErrors [GraphQL.Execution.UnhandledError: Error trying to resolve field 'previousBlock'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Libplanet.Explorer.GraphTypes.BlockType`1.<>c.<.ctor>b__0_7(IResolveFieldContext`1 ctx) in /home/longfin/9c-launcher/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet.Explorer/GraphTypes/BlockType.cs:line 67
```

I'll add `IStore` (perhap `MemoryStore`) implmentation for test project and execute them with a new `ExecuteAsync()` (non-generic version).

**Comment by longfin** [comment]
> Just note: even in 0.40.0, `BlockTypeTest.Query()` is failing under modifying a target query like as below. 😅
> 
> ```cs
>             var query =
>                 @"{
>                     index
>                     hash
>                     nonce
>                     difficulty
>                     totalDifficulty
>                     miner
>                     publicKey
>                     timestamp
>                     stateRootHash
>                     signature
>                     previousBlock { index }
>                 }";
> ```
> 
> ```
> Xunit.Sdk.NullException
> Assert.Null() Failure
> Expected: (null)
> Actual:   ExecutionErrors [GraphQL.Execution.UnhandledError: Error trying to resolve field 'previousBlock'.
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Libplanet.Explorer.GraphTypes.BlockType`1.<>c.<.ctor>b__0_7(IResolveFieldContext`1 ctx) in /home/longfin/9c-launcher/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet.Explorer/GraphTypes/BlockType.cs:line 67
> ```
> 
> I'll add `IStore` (perhap `MemoryStore`) implmentation for test project and execute them with a new `ExecuteAsync()` (non-generic version).

[63de318](https://github.com/planetarium/libplanet/pull/2186/commits/63de318620c247db2caa59ad3cfc0d971cec6f29) added. PTAL 🙏 @dahlia @moreal

**Review by dahlia — DISMISSED** [review]

**Comment by longfin** [comment]
Tests seems failing after [95fdb33](https://github.com/planetarium/libplanet/pull/2186/commits/95fdb3343aefd24066e8e1ef960926c45e3d58a8), I'll take a look now.

**Comment by longfin** [comment]
@moreal @dahlia https://github.com/planetarium/libplanet/pull/2186/commits/83f665e60949b59e0594003a5e7d77d8e8fe5bf7 amended.

`TransactionType<T>` also had assumed parameter-less `BlockType<T>`. so I provided custom service provider to testing scheme to suppress it. I guess it's very short-term workaround and unfavorable to maintenance. we may need to start discussion #2230 sooner than I thought.

**Pull request merged**
