### PR TITLE
Fix typo `Block<T>.CalcualteTxHashes()` to `Block<T>.CalculateTxHashes()`

### LINKED ISSUE #1303: Fix typo `Block<T>.CalcualteTxHashes()` to `Block<T>.CalculateTxHashes()`
The title says it all.

### PR DESCRIPTION
**Pull request by himanshu007-creator**
resolves #1303

### CODE REVIEW

**Comment by greymistcube** [comment]
Perhaps you might want to check other parts of the code? Since `CalculateTxHashes()` is a private method, the scope is pretty small, but there are references to it in the same file.

**Comment by greymistcube** [comment]
Sorry, I forgot to mention. For this project, every PR "requires" a changelog update, which is enforced by GitHub Actions. However, since this is only a simple typo fix for local usage, no real change is necessary to `CHANGES.md`. You can bypass this check by having `[skip changelog]` as part of your commit message. You can either amend the last commit and force push to the branch you were working on, or add an empty commit.

**Comment by greymistcube** [comment]
Hopefully one last thing. I would like to suggest slightly more descriptive commit message, so everyone knows why/how the edited file was affected.

**Comment by himanshu007-creator** [comment]
> Hopefully one last thing. I would like to suggest slightly more descriptive commit message, so everyone knows why/how the edited file was affected.

okay

**Comment by greymistcube** [comment]
Maybe I wasn't clear enough in https://github.com/planetarium/libplanet/pull/1306#issuecomment-843241845.

changelog_check

This needs to be resolved. You can see an example of `[skip changelog]` as part of a commit message in a [recently merged PR](https://github.com/planetarium/libplanet/pull/1283/commits).

**Review by dahlia — APPROVED** [review]

**Review by limebell — DISMISSED** [review]
👍

**Review by moreal — DISMISSED** [review]

**Review by longfin — APPROVED** [review]

**Review by dahlia — APPROVED** [review]
@planetarium/libplanet We should squash and merge this as it has too many commits.

**Pull request merged**
