### PR TITLE
🧹 Remove `StateStoreExtensions`

### LINKED ISSUE #3323: Cleanup `StateStoreExtension`
Certain methods are purely used only for testing. 🙄

### PR DESCRIPTION
**Pull request by greymistcube**
Resolves #3323.

### CODE REVIEW

**Review by riemannulus — COMMENTED** [review]
Does `StateStoreExteions` no longer exist use case? Have you been sure about `NineChronicles.Snapshot` too?

**Comment by greymistcube** [comment]
@riemannulus 
Eh, maybe you are right. I'll have to check. From the looks of it however:
- I believe whatever `NineChronicles.Snapshot` requires, it should be achievable using public APIs present.
- I don't see it as good enough reason to keep these extension methods around.

**Comment by riemannulus** [comment]
> I believe whatever NineChronicles.Snapshot requires, it should be achievable using public APIs present.

I agree with your opinion, but we need to move this extension(or function) to `NineChronicles.Snapshot` when it is used there. Just that much.

**Comment by greymistcube** [comment]
@riemannulus 
I Just checked, there is only a single instance of using `ContainsStateRoot()` which can be easily replaced. 😗

**Review by riemannulus — APPROVED** [review]

**Pull request merged**
