### PR TITLE
Fix a typo in `Libplanet.Explorer.Queries.Query.IsValidTransacion`

### LINKED ISSUE #1290: Typo in `Libplanet.Explorer.Queries.Query.IsValidTransacion`
There is [a typo `IsValidTransacion`](https://github.com/planetarium/libplanet/blob/e407618beb9157a1afa7649185e7e6d1ae75d9fb/Libplanet.Explorer/Queries/Query.cs#L203) but it should be `IsValidTransaction`.

### PR DESCRIPTION
**Pull request by himanshu007-creator**
resolves #1290

### CODE REVIEW

**Review by moreal — CHANGES_REQUESTED** [review]
Now, the build seems failed. Could you replace all `IsValidTransacion` with `IsValidTransaction`? There are two lines to use the changed method,  Libplanet.Explorer/Queries/ExplorerQuery.cs#L141 and Libplanet.Explorer/Queries/ExplorerQuery.cs#L167.

**Review by moreal — COMMENTED** [review]
Thanks to fix the build! One more step, how about using more meaningful commit message to describe what the commit changes? Like...

```
fix a typo

See  #1290 
```

**Review by longfin — APPROVED** [review]
Thanks for your first contribution! 🎉

**Review by dahlia — APPROVED** [review]

**Review by moreal — APPROVED** [review]

**Review by limebell — APPROVED** [review]
LGTM, thanks for the contribution.

**Pull request merged**
