### PR TITLE
Refactor: Move files to the following paths: src, test, tools

### PR DESCRIPTION
**Pull request by s2quake**
All projects within Libplanet.sln will move to the path shown below.

### src

- Libplanet
- Libplanet.Action
- Libplanet.Common
- Libplanet.Crypto.Secp256k1
- Libplanet.Crypto
- Libplanet.Net
- Libplanet.RocksDBStore
- Libplanet.Store.Remote
- Libplanet.Store
- Libplanet.Stun
- Libplanet.Types

### test

- Libplanet.Action.Tests
- Libplanet.Analyzers.Tests
- Libplanet.Crypto.Secp256k1.Tests
- Libplanet.Explorer.Cocona.Tests
- Libplanet.Explorer.Tests
- Libplanet.Extensions.Cocona.Tests
- Libplanet.Mocks
- Libplanet.Net.Tests
- Libplanet.RocksDBStore.Tests
- Libplanet.Store.Remote.Tests
- Libplanet.Stun.Tests
- Libplanet.Tests

### tools

- Libplanet.Analyzers
- Libplanet.Benchmarks
- Libplanet.Explorer.Cocona
- Libplanet.Explorer.Executable
- Libplanet.Explorer
- Libplanet.Extensions.Cocona
- Libplanet.Tools

### CODE REVIEW

**Comment by riemannulus** [comment]
Can we move it like this and move it later if needed?

**Comment by s2quake** [comment]
> Can we move it like this and move it later if needed?

Simply moving a project to a different path isn't difficult, but it's a little tricky because the project path (specifically `Libplanet.Tools`) affects ci operations.
I think it's relatively easy, except for the two things below.
* Rename `src`, `test`, `tools`.
* Change the location of `Libplanet.Tools` to something else.

**Comment by riemannulus** [comment]
Ok, merge after checking which has a dependency on libplanet.

**Review by riemannulus — APPROVED** [review]

**Review by limebell — DISMISSED** [review]
LGTM, please update PR to main branch :)

**Review by OnedgeLee — DISMISSED** [review]

**Review by greymistcube — APPROVED** [review]

**Review by greymistcube — APPROVED** [review]

**Pull request merged**
