### PR TITLE
More events on renderers

### PR DESCRIPTION
**Pull request by dahlia**
Added two more render methods:

- `IActionRenderer<T>.RenderBlockEnd()`
- `IRenderer<T>.RenderReorgEnd()`

See also the docs on `IRenderer<T>`:

IRenderer<T>

… and `IActionRenderer<T>`:

IActionRenderer<T>

By utilizing `RenderBlockEnd()` event, `DelayedActionRenderer<T>` became to atomically update its internal buffers (it's further than the approach made in #998).

I also refactored `DumRenderer<T>` (in the tests project) into `RecordingRenderer<T>` to reorganize `RenderRecord` into hierarchical layers.

### CODE REVIEW

**Review by limebell — CHANGES_REQUESTED** [review]
Newly introduced events should be listed on the `CHANGES.md`.

**Review by longfin — DISMISSED** [review]

**Review by earlbread — APPROVED** [review]

**Review by moreal — APPROVED** [review]

**Comment by dahlia** [comment]
> Newly introduced events should be listed on the `CHANGES.md`.

As `IRenderer<T>` & `IActionRenderer<T>` have never been released yet, I didn't list them on the changelog.

**Review by riemannulus — DISMISSED** [review]

**Review by limebell — DISMISSED** [review]

**Comment by limebell** [comment]
I guess we should add it [here](https://github.com/planetarium/libplanet/blob/main/CHANGES.md#L18) at least?

**Comment by dahlia** [comment]
> I guess we should add it [here](https://github.com/planetarium/libplanet/blob/main/CHANGES.md#L18) at least?

@limebell Okay, I'm going to add it there.

**Comment by dahlia** [comment]
@planetarium/libplanet Added missing unit tests and changelogs! Please review this again.

**Review by longfin — APPROVED** [review]

**Review by limebell — APPROVED** [review]

**Review by earlbread — APPROVED** [review]

**Review by riemannulus — APPROVED** [review]

**Pull request merged**
