### PR TITLE
Fixed a typo in transaction.cs on line 399

### LINKED ISSUE #1376: Typo in `Libplanet.Tx.Transaction<T>.Create()` method's docs
There is a sentence to describe when the exception will be thrown, `Thrown when null is passed to privateKey or or actions.`.
To me, the continuous two `or`s look like a typo. https://github.com/planetarium/libplanet/blob/d3ea9492145db52d4b0295b2d87b333b2b2c51a2/Libplanet/Tx/Transaction.cs#L398-L399

image

P.S. If it is correct grammer which I don't know, you can close this issue anytime.

### PR DESCRIPTION
**Pull request by dineshkumar12004**
Fixed a  typo in line 399 of transaction.cs. 
Closes #1376

image

### CODE REVIEW

**Comment by longfin** [comment]
@dineshkumar12004 Thanks for your contribution! 

We're using the checker for changelog keeping and your PR doesn't seem to need to be written to the changelog. 
so, could you add `[skip changelog]` to the commit message to bypass the checker?

**Comment by dineshkumar12004** [comment]
so i have to push the code again ? @longfin by writing new commit message ? I'm kinda new to this can you breif

**Comment by dahlia** [comment]
@dineshkumar12004 You don't have to *add* a more commit, but you just need [*amend* your existing commit message][1].

[1]: https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by dineshkumar12004** [comment]
I made  the changes, is this good enough @longfin

**Comment by dahlia** [comment]
@dineshkumar12004 It seems okay now.  Thanks for your contribution!

**Review by dahlia — APPROVED** [review]

**Comment by dineshkumar12004** [comment]
Thank you so much for guiding me @dahlia looking forward to contribute more :)

**Pull request merged**
