### PR TITLE
Remove sonar analyzer surpressions

### PR DESCRIPTION
**Pull request by stylesm**
Removed surpression of S4201, 21125, S1450, S2234, S3358, S3442 Sonar Analyzer errors.

SA1481 is outstanding.

### CODE REVIEW

**Review by moreal — APPROVED** [review]
Thanks for your first contribution! 👍 It looks good to me. 😎 However, the *4035* suppression also seems removed but not mentioned in the pull request description. Could you update it? @stylesm

**Review by limebell — APPROVED** [review]
LGTM

**Review by limebell — CHANGES_REQUESTED** [review]
Something went wrong during rebasing I guess... Please check commits.

**Review by longfin — APPROVED** [review]
Thanks for your first contribution! it looks good to me.

p.s. Some tests are failing now. but I guess they're false-positive. 😅

**Review by dahlia — APPROVED** [review]

**Review by limebell — APPROVED** [review]

**Pull request merged**
