### PR TITLE
Consider nonexistent chain as an empty chain

### LINKED ISSUE #2047: Fix a `ChainIdNotFoundException` when transaction was never run
https://github.com/planetarium/libplanet/blob/main/Libplanet/Blockchain/BlockChain.cs#L1192
If it ran PreloadAsync after creating a clean blockchain where no transactions have been created, `ChainIdNotFoundException` occurs.
When no transactions are created, I think need to skip

### PR DESCRIPTION
**Pull request by tkiapril**
Resolves #2047.
With this PR, nonexistent chain ids in `IStore` are considered to be chain ids with empty chains, thus fixing the bug when empty block collections or `TxNonce` collections are to be forked.

### CODE REVIEW

**Comment by tkiapril** [comment]
A concern for `RocksDBStore`: In `ForkBlockIndexes`, as with when `branchpoint` is same as the `genesisHash`, when `genesisHash` is null (there are no blocks associated with the chain id,) I made it so that the function does nothing and return. I believe this is logically okay as it didn't break any (previously not broken) tests, but I was wondering if I would have had to do create `PreviousChainId`, `PreviousChainIndex`, `IndexCount`, `ChainId` and do `AddFork` for the (both empty) chain ids. It wouldn't be a problem since other operations on nonexistent chain id should return appropriate values indicating nonexistent chain (be it an empty collection, `null`, or `0`,) but I was wondering if there may be some places with codes that do not work accordingly when there are no `PreviousChainId` etc.

**Comment by greymistcube** [comment]
Also can we add test cases for using `DefaultStore` and `RocksDBStore` to `StoreTest.cs`?

**Comment by tkiapril** [comment]
> Also can we add test cases for using `DefaultStore` and `RocksDBStore` to `StoreTest.cs`?
Good idea, though tests using `RocksDBStore` is broken atm. (#2155) Should I be adding Libplanet.RocksDBStore as a dependency to Libplanet.Tests or does that make any sense?

**Review by dahlia — APPROVED** [review]

**Review by dahlia — APPROVED** [review]

**Comment by tkiapril** [comment]
#2159 should be merged first for the tests to not fail.

**Comment by dahlia** [comment]
#2159 has just been merged.  Could you rebase it on the current *main*?  There seems a conflict on *CHANGES.md* file.

**Comment by tkiapril** [comment]
@dahlia Done!

**Review by dahlia — APPROVED** [review]

**Review by longfin — APPROVED** [review]

**Review by dahlia — APPROVED** [review]

**Pull request merged**
