### PR TITLE
Fixed typo

### LINKED ISSUE #393: Typo in Swarm
There are sentences like `An unexpected exception occured during DoBroadcast()`.
Every `occured` should be `occurred`.

### PR DESCRIPTION
**Pull request by kashifsoofi**
Changed all occurrences of occured to occurred.
Fixes #393

### CODE REVIEW

**Comment by kashifsoofi** [comment]
> 
> 
> > Already signed CLA, not sure why its not coming up.
> 
> Maybe it's because you didn't [add the email address used for this commit to your account](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user). Could you please check your GitHub email setting? @kashifsoofi

Done. Was using wrong email :(

**Comment by dahlia** [comment]
Thank you!

**Pull request merged**
