### PR TITLE
♻️ Remove `Rehearsal` from `IActionContext`

### PR DESCRIPTION
**Pull request by greymistcube**
♻️ In preparation for version 4.0.0. `DumbAction` needs to be refactored further to remove `RecordRehearsal` property at some point. 🙄

### CODE REVIEW

**Comment by riemannulus** [comment]
The build seems failed.

**Comment by greymistcube** [comment]
Eh, for whatever reason, builds are being flaky now. Manual retries seem to fix the issues. 🙄

**Comment by riemannulus** [comment]
I'm worried that there will be too many API changes... but this PR is nothing to the problem.

**Review by riemannulus — APPROVED** [review]

**Comment by riemannulus** [comment]
Check when you bump to lib9c and more. They have their own `IActionContext` serializer. (lib9c, headless, unity)

**Comment by greymistcube** [comment]
@riemannulus
Hence I've preemptively worked on removing references to `Rehearsal` from [lib9c](https://github.com/planetarium/lib9c) as seen [here](https://github.com/planetarium/lib9c/pull/2222) and [here](https://github.com/planetarium/lib9c/pull/2224) to make the transition as smooth as possible.

**Comment by riemannulus** [comment]
Ah, yes we use `ICommitedActionContext` when calling render event. I missed. 😆

**Pull request merged**
